# Generated by Django 4.2.2 on 2023-07-19 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('book_image_url', models.URLField()),
                ('description', models.TextField()),
                ('total_copy', models.IntegerField(default=0)),
                ('first_pub', models.DateField(auto_now_add=True)),
                ('last_pub', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mystery', 'Mystery'), ('thriller', 'Thriller'), ('sci_fi', 'Sci-Fi'), ('humor', 'Humor'), ('horror', 'Horror'), ('novel', 'Novel'), ('bengali classic novel', 'Bengali Classic Novel'), ('sucpence', 'Sucpence'), ('short_story', 'Short Story'), ('romance', 'Romance'), ('modern', 'Modern'), ('retro', 'Retro'), ('history', 'History'), ('religious', 'Religious'), ('documentary', 'Documentary'), ('self help', 'Self Help'), ('high life spirituality', 'High Life Spirituality'), ('how to', 'How To'), ('bengali novel', 'Bengali Novel'), ('poem collections', 'Poem Collections')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now=True)),
                ('provisional_return_date', models.DateTimeField(default=datetime.datetime(2023, 8, 3, 13, 11, 4, 460383, tzinfo=datetime.timezone.utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('is_fine_paid', models.BooleanField(default=False)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book', to='books.borrowbook')),
            ],
        ),
    ]
