# Generated by Django 4.2.2 on 2023-07-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('original_book_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('has_book_added_in_library', models.BooleanField(default=False)),
                ('is_form_request', models.BooleanField(default=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
