# Generated by Django 4.2.2 on 2023-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
