# Generated by Django 4.2.2 on 2023-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='total_borrowed_books',
            field=models.IntegerField(default=0),
        ),
    ]
